import type { Metadata } from "next";
import { Hind_Siliguri, Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

const banglaFont = Hind_Siliguri({
  subsets: ['bengali'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-bangla',
});

export const metadata: Metadata = {
  title: "RENT NEST",
  description: "Generated by MD AL HELAL SARKER",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn" className={`${roboto.variable} ${banglaFont.variable}`}>
      <body className="min-h-full flex flex-col bg-olive-300" suppressHydrationWarning>
        <TooltipProvider>
         {children}
        </TooltipProvider>
         <Toaster richColors closeButton />
      </body>
    </html>
  );
}